apiVersion: v1
kind: Pod
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.6.0-debug
      securityContext:
        runAsUser: 0
      command:
        - sleep
      args:
        - 99d
      volumeMounts:
        - name: fabric-builds
          mountPath: /kaniko/.docker
    - name: maven
      image: maven:3.8-openjdk-17
      command:
        - sleep
      args:
        - 99d
  volumes:
    - name: fabric-builds
      emptyDir: { }
  imagePullSecrets:
    - name: nexusregcred